services:
  dream-league-api:
    extends:
      file: compose.yaml
      service: dream-league-api
    build:
      target: development
    command: >
      sh -c "
        npm run migrate &&
        npm run seed &&
        npm run test"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
      - ./test/:/home/node/test/
      - ./test-output/:/home/node/test-output/
    depends_on:
      dream-league-api-postgres:
        condition: service_healthy

  dream-league-api-postgres:
    extends:
      file: compose.yaml
      service: dream-league-api-postgres
    container_name: dream-league-api-postgres-test
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
