services:
  dream-league-api:
    build:
      context: .
      target: development
    depends_on:
      - dream-league-api-postgres
    environment:
      POSTGRES_HOST: dream-league-api-postgres
    command: >
      sh -c "
        scripts/wait-for dream-league-api-postgres:5432 --
        npm run migrate &&
        npm run seed &&
        npm run test"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
      - ./test/:/home/node/test/
      - ./test-output/:/home/node/test-output/

  dream-league-api-postgres:
    container_name: dream-league-api-postgres-test
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
