version: '3.7'
services:
  dream-league-identity:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment: 
      JWT_SECRET: secret
      POSTGRES_HOST: dream-league-identity-postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    command: >
      sh -c "
        scripts/wait-for/wait-for dream-league-identity-postgres:5432 --
        npm run migrate &&
        npm run seed &&
        npm run start:watch"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json

  dream-league-identity-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: dream_league_identity
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
