version: '3.7'
services:
  dream-league-api:
    build: .
    image: dream-league-api
    container_name: dream-league-api
    environment: 
      JWT_SECRET: secret
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

  dream-league-api-postgres:
    image: postgres:12.8-alpine
    container_name: dream-league-api-postgres
    environment:
      POSTGRES_DB: dream_league_api
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
