version: '3.7'
services:
  dream-league-api:
    build: .
    image: dream-league-api
    container_name: dream-league-api
    environment: 
      JWT_SECRET: secret
      POSTGRES_HOST: dream-league-api-postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres

  dream-league-api-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: dream_league_api
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
