version: '3.7'
services:
  dream-league-api:
    build:
      context: .
      target: development
    environment:
      POSTGRES_HOST: dream-league-api-postgres
    ports:
      - "3001:3001"
      - "9230:9229"
    command: >
      sh -c "
        scripts/wait-for dream-league-api-postgres:5432 --
        npm run migrate &&
        npm run seed &&
        npm run start:watch"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
      - ./test/:/home/node/test/
      - ./test-output/:/home/node/test-output/

  dream-league-api-postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
