version: '3.7'
services:
  dream-league-api:
    build: .
    image: dream-league-api
    container_name: dream-league-api
    environment: 
      JWT_SECRET: secret      
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
