sonar.projectKey=johnwatson484_dream-league-api
sonar.organization=johnwatson484

sonar.links.homepage=https://github.com/johnwatson484/dream-league-api
sonar.links.ci=https://github.com/johnwatson484/dream-league-api/actions
sonar.links.scm=https://github.com/johnwatson484/dream-league-api
sonar.links.issue=https://github.com/johnwatson484/dream-league-api/issues

sonar.sources=app/
sonar.exclusions=test/**/*.test.js
sonar.tests=test/

sonar.javascript.lcov.reportPaths=./coverage/lcov.info

sonar.cpd.exclusions=test/
