apiVersion: v2
name: dream-league-api
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
dependencies:
- name: helm-library
  version: 2.12.0
  repository: https://helm.lynxmagnus.com
