environment: production
name: dream-league-api
image: dream-league-api

container:
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 1000Mi
  limitCpu: 1000m
  port: 3001
  jwtSecret: secret
  jwtExpiryInMinutes: 43800
  command: ["/bin/sh"]
  args: ["-c", "npx sequelize-cli db:migrate && node app"]
  smtpHost:
  smtpUser:
  smtpPassword:
  webUrl: https://www.dreamleaguefantasyfootball.co.uk
  redisHost:
  redisPassword:
  messageHost:
  messagePort: 5672
  messageUsername:
  messagePassword:
  scoreExchange: live-scores
  scoreQueue: dream-league-api

postgresService:
  postgresHost: dream-league-api-postgres
  postgresPort: 5432
  postgresUsername: postgres
  postgresPassword: postgres
  postgresDatabase: dream_league_api

deployment:
  minReplicas: 1
  maxReplicas: 5
  cpuThreshold: 80
  memoryThreshold: 80
  triggerQueueLength: 50

secret:
  type: Opaque
