environment: production
name: dream-league-api
image: dream-league-api

container:
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 1000Mi
  limitCpu: 1000m
  port: 3001
  jwtExpiryInMinutes: 43800
  command: ["/bin/sh"]
  args: ["-c", "npx sequelize-cli db:migrate && node app"]
  smtpHost: smtp.zoho.com
  webUrl: https://www.dreamleaguefantasyfootball.co.uk
  redisHost: services.lynxmagnus.com
  messageHost: services.lynxmagnus.com
  messagePort: 5672
  scoreExchange: live-scores
  scoreQueue: dream-league-api

postgresService:
  postgresHost: services.lynxmagnus.com
  postgresPort: 5432
  postgresDatabase: dream_league_api

deployment:
  minReplicas: 1
  maxReplicas: 5
  cpuThreshold: 80
  memoryThreshold: 80
  triggerQueueLength: 50

secret:
  secretsPath: /dream-league-api
