environment: development
name: dream-league-api
image: dream-league-api

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 60Mi
  limitCpu: 60m
  port: 3000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  jwtSecret: secret
  jwtExpiryInMinutes: 60
  command: ["/bin/sh"]
  args: ["-c", "npm run migrate && npm run seed && npm run start"]

postgresService:
  postgresHost: dream-league-api-postgres
  postgresExternalName: host.docker.internal
  postgresPort: 5432
  postgresUsername: postgres
  postgresPassword: postgres
  postgresDatabase: dream_league_api

deployment:
  restartPolicy: Always
  replicas: 1
  minReadySeconds: 5
  redeployOnChange: update this field to force a change
  imagePullSecret:
  runAsNonRoot: true
  runAsUser: 1000

service:
  port: 80
