environment: production
name: dream-league-api
image: dream-league-api

container:
  resourceTier: M
  port: 3001  
  command: ["/bin/sh"]
  args: ["-c", "npx sequelize-cli db:migrate && node app"]

config:
  jwtExpiryInMinutes: 43800
  webUrl: https://www.dreamleaguefantasyfootball.co.uk

smtp:
  host: smtp.zoho.com

redis:
  host: services.lynxmagnus.com
  
rabbit:
  host: services.lynxmagnus.com
  scoreExchange: live-scores
  scoreQueue: dream-league-api

postgres:
  host: services.lynxmagnus.com
  port: 5432
  database: dream_league_api

deployment:
  minReplicas: 1
  maxReplicas: 4
  triggerQueueLength: 50
  cpuThreshold: 80
  memoryThreshold: 80

secret:
  secretsPath: /dream-league-api
