INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (2, 1993, 7, 'Billy Gordon', NULL, NULL, NULL, NULL);
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (3, 1994, 14, 'Ray Havard', NULL, NULL, NULL, NULL);
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (4, 1995, 13, 'Ray Havard', NULL, 'Ray Havard', 'Neville Atkinson', NULL);
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (5, 1996, 12, 'Ali Lambie', NULL, 'Brian English', 'Ali Lambie', NULL);
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (6, 1997, 16, 'Frank Rowe', NULL, 'Gavin O''Donnell', 'Frank Rowe', NULL);
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (7, 1998, 16, 'Gavin O''Donnell', NULL, 'Steve Cammish', 'Tommy Gordon', NULL);
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (8, 1999, 16, 'Pete Nyland', NULL, 'Pete Nyland', 'Andy Vincent', NULL);
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (9, 2000, 16, 'Pete Nyland', 'Tommy Gordon', 'Steve Cammish', 'Ali Lambie', NULL);
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (10, 2001, 16, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (11, 2002, 16, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (12, 2003, 16, 'Lee Gordon', NULL, NULL, NULL, NULL);
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (13, 2004, 16, NULL, NULL, 'Steve Nendick', NULL, NULL);
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (14, 2005, 16, NULL, NULL, 'Andrew Jerry', NULL, 'Frank Rowe');
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (15, 2006, 14, 'Lee Gordon', 'Steve Nendick', 'Steve Nendick', NULL, 'Andrew Jerry');
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (16, 2007, 9, 'Pete Nyland', NULL, 'Pete Nyland', NULL, 'Lee Gordon');
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (17, 2008, 10, 'Steve Nendick', NULL, 'Doug Jerry', NULL, 'Mark Forster');
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (18, 2009, 9, 'Tommy Gordon', NULL, 'Frank Rowe', NULL, 'Tommy Gordon');
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (19, 2010, 12, 'Billy Gordon', NULL, 'Frank Rowe', NULL, 'Lee Gordon');
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (20, 2011, 12, 'Tommy Gordon', NULL, 'Tommy Gordon', NULL, 'Tommy Gordon');
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (21, 2012, 15, 'David Brown', NULL, 'Mark Forster', NULL, 'Lee Gordon');
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (22, 2013, 15, 'Steve Nendick', NULL, 'Tommy Gordon', NULL, 'Tommy Gordon');
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (23, 2014, 14, 'David Brown', NULL, 'Tommy Gordon', NULL, 'Michael Richardson');
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (24, 2015, 13, 'Michael Richardson', NULL, 'Pete Nyland', NULL, 'Michael Richardson');
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (25, 2016, 12, 'David Brown', NULL, 'David Brown', NULL, 'Karl Brazier');
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (26, 2017, 11, 'Karl Brazier', NULL, 'Lee Gordon', NULL, 'Karl Brazier');
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (27, 2018, 13, 'Pete Nyland/Frank Rowe', NULL, 'Pete Nyland/Frank Rowe', NULL, 'Billy Gordon');
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (28, 2019, 14, 'Pete Nyland/Frank Rowe', NULL, 'David Brown', NULL, 'Pete Nyland/Frank Rowe');
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (29, 2020, 13, 'Lee Gordon', NULL, '*Abandoned', NULL, '*Abandoned');
INSERT INTO "history" ("historyId", "year", "teams", "league1", "league2", "cup", "plate", "leagueCup") VALUES (30, 2021, 12, 'Bob Brown', NULL, 'Lee Gordon', NULL, 'Lee Gordon');
