{{- define "dream-league-api.container" -}}
envFrom:
- configMapRef:
    name: {{ .Values.name }}
- secretRef:
    name: {{ .Values.name }}-infiscal-secret
ports:
- containerPort: {{ .Values.container.port }}
  name: http
  protocol: TCP
{{- end -}}
