{{- include "helm-library.configmap" (list . "dream-league-api.configmap") -}}
{{- define "dream-league-api.configmap" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}  
  REDIS_HOST: {{ quote .Values.redis.host }}
  MESSAGE_HOST: {{ quote .Values.rabbit.host }}
  SCORE_EXCHANGE: {{ quote .Values.rabbit.scoreExchange }}
  SCORE_QUEUE: {{ quote .Values.rabbit.scoreQueue }}
  POSTGRES_HOST: {{ quote .Values.postgres.host }}
  POSTGRES_PORT: {{ quote .Values.postgres.port }}
  POSTGRES_DB: {{ quote .Values.postgres.database }}
  SMTP_HOST: {{ quote .Values.smtp.host }}
  JWT_EXPIRY_IN_MINUTES: {{ quote .Values.config.jwtExpiryInMinutes }}
  WEB_URL: {{ quote .Values.config.webUrl }}
{{- end -}}
