apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Chart.Name }}
spec:
  scaleTargetRef:
    name: {{ .Chart.Name }}
  minReplicaCount: {{ .Values.deployment.minReplicas }}
  maxReplicaCount: {{ .Values.deployment.maxReplicas }}
  triggers:
  - type: rabbitmq
    metadata:
      hostFromEnv: MESSAGE_HOST_STRING
      queueName: {{ .Values.rabbit.scoreQueue }}
      mode: QueueLength
      value: {{ .Values.deployment.triggerQueueLength | quote }}
  - type: cpu
    metricType: Utilization
    metadata:
      value: {{ .Values.deployment.cpuThreshold | quote }}
  - type: memory
    metricType: Utilization
    metadata:
      value: {{ .Values.deployment.memoryThreshold | quote }}
