{{- include "helm-library.keda-scaled-object" (list . "dream-league-api.keda-scaled-object") -}}
{{- define "dream-league-api.keda-scaled-object" -}}
spec:
  triggers:
  - type: rabbitmq
    metadata:
      hostFromEnv: MESSAGE_HOST_STRING
      queueName: {{ .Values.rabbit.scoreQueue }}
      mode: QueueLength
      value: {{ .Values.deployment.triggerQueueLength | quote }}
  - type: cpu
    metricType: Utilization
    metadata:
      value: {{ .Values.deployment.cpuThreshold | quote }}
  - type: memory
    metricType: Utilization
    metadata:
      value: {{ .Values.deployment.memoryThreshold | quote }}
{{- end -}}
