apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.name }}
spec:
  scaleTargetRef:
    name: {{ .Values.name }}
  minReplicaCount: {{ .Values.deployment.minReplicas | quote }}
  maxReplicaCount: {{ .Values.deployment.maxReplicas | quote }}
  triggers:
  - type: rabbitmq
    metadata:
      hostFromEnv: MESSAGE_HOST_STRING
      queueName: {{ .Values.container.scoreQueue }}
      mode: QueueLength
      value: {{ .Values.deployment.triggerQueueLength | quote }}
