apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.name }}
spec:
  scaleTargetRef:
    name: {{ .Values.name }}
  triggers:
  - type: rabbitmq
    metadata:
      host: MESSAGE_HOST
      queueName: {{ .Values.container.scoreQueue }}
      mode: QueueLength
      value: {{ .Values.deployment.triggerQueueLength | quote }}
      minReplicaCount: {{ .Values.deployment.minReplicas | quote }}
      maxReplicaCount: {{ .Values.deployment.maxReplicas | quote }}
