{{- include "helm-library.secret" (list . "dream-league-api.secret") -}}
{{- define "dream-league-api.secret" -}}
stringData:
  JWT_SECRET: {{ quote .Values.container.jwtSecret }}
  SMTP_USER: {{ quote .Values.container.smtpUser }}
  SMTP_PASSWORD: {{ quote .Values.container.smtpPassword }}
  POSTGRES_USERNAME: {{ quote .Values.postgresService.postgresUsername }}
  POSTGRES_PASSWORD: {{ quote .Values.postgresService.postgresPassword }}
  REDIS_PASSWORD: {{ quote .Values.container.redisPassword }}
  MESSAGE_USERNAME: {{ quote .Values.container.messageUsername }}
  MESSAGE_PASSWORD: {{ quote .Values.container.messagePassword }}
{{- end -}}
